"""Add badge definition conditions

Revision ID: 2221cef460ad
Revises: ff7a3eb46757
Create Date: 2025-05-04 18:43:41.729655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2221cef460ad'
down_revision: Union[str, None] = 'ff7a3eb46757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge_definitions', sa.Column('min_streak', sa.Integer(), nullable=True))
    op.add_column('badge_definitions', sa.Column('min_matches', sa.Integer(), nullable=True))
    op.add_column('badge_definitions', sa.Column('badge_type', sa.String(), nullable=True))
    op.add_column('badge_definitions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'badge_definitions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'badge_definitions', type_='unique')
    op.drop_column('badge_definitions', 'created_at')
    op.drop_column('badge_definitions', 'badge_type')
    op.drop_column('badge_definitions', 'min_matches')
    op.drop_column('badge_definitions', 'min_streak')
    # ### end Alembic commands ###
