"""expand vibe_question_type enum

Revision ID: 560a773a8b61
Revises: 3b870100f5ab
Create Date: 2025-05-11 01:12:34.963269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560a773a8b61'
down_revision: Union[str, None] = '3b870100f5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'date_picker'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'time_picker'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'swipe'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'single_choice'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'multi_choice'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'true_false'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'emoji_choice'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'image_choice'")
    op.execute("ALTER TYPE vibe_question_type ADD VALUE IF NOT EXISTS 'scale_rating'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
