"""Add pair_streaks table

Revision ID: 62e5b77cc8a8
Revises: 2221cef460ad
Create Date: 2025-05-04 23:37:58.499130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e5b77cc8a8'
down_revision: Union[str, None] = '2221cef460ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair_streaks',
    sa.Column('streak_id', sa.String(), nullable=False),
    sa.Column('pair_id', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['partner_pairing.pair_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('streak_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pair_streaks')
    # ### end Alembic commands ###
