"""add pairing_status and pair_status columns

Revision ID: 6785a2d21b14
Revises: 9d1bf68ffdb8
Create Date: 2025-04-20 03:42:27.957458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6785a2d21b14'
down_revision: Union[str, None] = '9d1bf68ffdb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_pairing', sa.Column('pair_status', sa.String(), server_default='active', nullable=False))
    op.create_index(op.f('ix_partner_pairing_pair_id'), 'partner_pairing', ['pair_id'], unique=False)
    op.add_column('users', sa.Column('pairing_status', sa.String(), server_default='single', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pairing_status')
    op.drop_index(op.f('ix_partner_pairing_pair_id'), table_name='partner_pairing')
    op.drop_column('partner_pairing', 'pair_status')
    # ### end Alembic commands ###
