"""add user_relationship_settings table

Revision ID: 8d3ce1c67bc0
Revises: a195361a8c0e
Create Date: 2025-05-21 21:01:48.678142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3ce1c67bc0'
down_revision: Union[str, None] = 'a195361a8c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationship_settings',
    sa.Column('settings_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('pair_id', sa.String(), nullable=True),
    sa.Column('intentions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('living_situation', sa.String(), nullable=True),
    sa.Column('anniversary', sa.Date(), nullable=True),
    sa.Column('current_emotion', sa.String(), nullable=True),
    sa.Column('preferred_relationship_type', sa.String(), nullable=True),
    sa.Column('is_active_pair', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['single_vibe_paired_users.pair_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('settings_id')
    )
    op.create_index(op.f('ix_user_relationship_settings_settings_id'), 'user_relationship_settings', ['settings_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_relationship_settings_settings_id'), table_name='user_relationship_settings')
    op.drop_table('user_relationship_settings')
    # ### end Alembic commands ###
