"""create partner_pairing table

Revision ID: 9d1bf68ffdb8
Revises: 439c6332cef7
Create Date: 2025-04-20 03:22:50.602997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1bf68ffdb8'
down_revision: Union[str, None] = '439c6332cef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_pairing',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pair_id')
    )
    # op.create_index(op.f('ix_partner_pairing_pair_id'), 'partner_pairing', ['pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_partner_pairing_pair_id'), table_name='partner_pairing')
    op.drop_table('partner_pairing')
    # ### end Alembic commands ###
