"""add_onboarding_fields_to_user_model

Revision ID: a9abe8e9422a
Revises: 245ce8e9308a
Create Date: 2025-05-23 01:18:00.405333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9abe8e9422a'
down_revision: Union[str, None] = '245ce8e9308a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vibe_keywords', sa.String(), nullable=True))
    op.add_column('users', sa.Column('education', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('relationship_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('onboarded', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('height', sa.String(), nullable=True))
    op.add_column('users', sa.Column('audio_intro', sa.String(), nullable=True))
    op.add_column('users', sa.Column('video_intro', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image_gallery', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_number')
    op.drop_column('users', 'image_gallery')
    op.drop_column('users', 'video_intro')
    op.drop_column('users', 'audio_intro')
    op.drop_column('users', 'height')
    op.drop_column('users', 'onboarded')
    op.drop_column('users', 'relationship_goal')
    op.drop_column('users', 'location')
    op.drop_column('users', 'education')
    op.drop_column('users', 'vibe_keywords')
    # ### end Alembic commands ###
