"""add vibe question day mapping table

Revision ID: c1b14c9b9b4c
Revises: 560a773a8b61
Create Date: 2025-05-11 02:59:33.471404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b14c9b9b4c'
down_revision: Union[str, None] = '560a773a8b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vibe_question_day_mapping',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('days_condition', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['vibe_questions.question_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vibe_question_day_mapping')
    # ### end Alembic commands ###
