"""Add answer_matched column

Revision ID: d646301ab4f7
Revises: 62e5b77cc8a8
Create Date: 2025-05-05 00:39:37.322619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd646301ab4f7'
down_revision: Union[str, None] = '62e5b77cc8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mystery_moodbox_prompted_questions', sa.Column('answer_matched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mystery_moodbox_prompted_questions', 'answer_matched')
    # ### end Alembic commands ###
