"""Add device_id to User model

Revision ID: e1bda5ad13bc
Revises: 6785a2d21b14
Create Date: 2025-04-26 01:19:56.924708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bda5ad13bc'
down_revision: Union[str, None] = '6785a2d21b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'device_id')
    # ### end Alembic commands ###
