"""Add answer column to prompted questions

Revision ID: fb234ddd3bd5
Revises: 046aa6159268
Create Date: 2025-05-04 16:37:53.922158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb234ddd3bd5'
down_revision: Union[str, None] = '046aa6159268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mystery_moodbox_prompted_questions', sa.Column('answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mystery_moodbox_prompted_questions', 'answer')
    # ### end Alembic commands ###
