"""Rename id to pair_badge_id in pair_badges

Revision ID: ff7a3eb46757
Revises: fb234ddd3bd5
Create Date: 2025-05-04 18:04:00.973701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7a3eb46757'
down_revision: Union[str, None] = 'fb234ddd3bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_definitions',
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('pair_badges',
    sa.Column('pair_badge_id', sa.String(), nullable=False),
    sa.Column('pair_id', sa.String(), nullable=False),
    sa.Column('badge_id', sa.String(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge_definitions.badge_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pair_id'], ['partner_pairing.pair_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pair_badge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pair_badges')
    op.drop_table('badge_definitions')
    # ### end Alembic commands ###
